defaults: &defaults
  working_directory: ~/working_directory
  steps:
    - checkout
    - run: ./travis/run.sh

version: 2
jobs:
  build-php56:
    <<: *defaults
    docker:
      - image: php:5.6
  build-php70:
    <<: *defaults
    docker:
      - image: php:7.0
  build-python27:
    <<: *defaults
    docker:
      - image: python:2.7

workflows:
  version: 2
  build:
    jobs:
      - build-php56
      - build-php70
      - build-python27
